import streamlit as st

st.set_page_config(page_title="Crush Predictor", page_icon="💘")

st.title("💘 Crush Predictor — Documentation")

st.header("What is this?")
st.write("""
This is a Machine Learning based web app that predicts the **chance (%) that your crush likes you back**, based on 10 behavioral signals.
""")

st.subheader("Model & Dataset")
st.write("""
- Model Used: **Random Forest Regressor**  
- Training data: Dummay dataset generated by me.
- Accuracy: **77%**  
- Inputs: 10 behavior features  
- Output: Probability (0–100%)
""")

st.subheader("🎯 Input Fields")
st.write("""
    1. 💬 Do they start conversations with you?,
    2. 🎧 Do they seem interested when you talk?,
    3. 📱 Do they reply quickly to your messages?,
    4. 👀 Do they make eye contact often?,
    5. 😄 Do they joke around with you?,
    6. 😬 Do they seem nervous around you sometimes?,
    7. 🧍‍♂️ Do they stay close to you in groups?,
    8. 🤝 Do they help you when you need it?,
    9. 😊 Do they smile a lot around you?,
    10. 🎉 Do they invite you to hang out?  
""")
st.write("""
The user evaluates behavioral signals on a scale from 1 to 10. The model then analyzes these inputs to predict the likelihood (%) of your crush liking you back.
""")

st.success("Go to the **Prediction** page from the sidebar!")

st.divider()
st.write("""
Made With ❤️ by Prashant Gupta. A fun project to learn mahine learning.
""")
st.link_button("GitHub", "https://www.github.com/prashant-g0")
st.link_button("LinkedIn", "https://www.linkedin.com/in/prashant-g0")

